/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Home': RouteRecordInfo<'Home', '/', Record<never, never>, Record<never, never>>,
    'Account': RouteRecordInfo<'Account', '/account', Record<never, never>, Record<never, never>>,
    'ChangeEmail': RouteRecordInfo<'ChangeEmail', '/change-email', Record<never, never>, Record<never, never>>,
    'ForgotPassword': RouteRecordInfo<'ForgotPassword', '/forgot-password', Record<never, never>, Record<never, never>>,
    'Login': RouteRecordInfo<'Login', '/login', Record<never, never>, Record<never, never>>,
    'Post': RouteRecordInfo<'Post', '/post/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    'ResetPassword': RouteRecordInfo<'ResetPassword', '/reset-password', Record<never, never>, Record<never, never>>,
    'SignUp': RouteRecordInfo<'SignUp', '/signup', Record<never, never>, Record<never, never>>,
    'Taps': RouteRecordInfo<'Taps', '/taps', Record<never, never>, Record<never, never>>,
    'Timeline': RouteRecordInfo<'Timeline', '/timeline', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: 'Home'
      views: never
    }
    'src/pages/account.vue': {
      routes: 'Account'
      views: never
    }
    'src/pages/change-email.vue': {
      routes: 'ChangeEmail'
      views: never
    }
    'src/pages/forgot-password.vue': {
      routes: 'ForgotPassword'
      views: never
    }
    'src/pages/login.vue': {
      routes: 'Login'
      views: never
    }
    'src/pages/post/[id].vue': {
      routes: 'Post'
      views: never
    }
    'src/pages/reset-password.vue': {
      routes: 'ResetPassword'
      views: never
    }
    'src/pages/signup.vue': {
      routes: 'SignUp'
      views: never
    }
    'src/pages/taps.vue': {
      routes: 'Taps'
      views: never
    }
    'src/pages/timeline.vue': {
      routes: 'Timeline'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
